repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.12
    hooks:
      - id: actionlint
        language: golang
        additional_dependencies:
          - github.com/wasilibs/go-shellcheck/cmd/shellcheck@v0.11.1
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 43.262.0
    hooks:
      - id: renovate-config-validator
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.14.2
    hooks:
      - id: markdown-link-check
        args: [-q]
  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint-docker
