# Workaround for sysusers.d bug that removes root user from /etc/shadow in initramfs, preventing SSH login.
# TODO: Remove once the bug is fixed.
# TODO: verify on AlmaLinux EL10
[Service]
ExecStartPre=+/bin/sh -c 'echo "root:*:0::::::" >> /etc/shadow'
